export const LOAD_MATCHES_SUCCESS = 'LOAD_MATCHES_SUCCESS';
export const LOAD_STANDINGS_SUCCESS = 'LOAD_STANDINGS_SUCCESS';
export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
export const LOAD_COMPETITION = 'LOAD_COMPETITION';
