export const LOAD_COMPETITION = 'LOAD_COMPETITION';

export const SET_DISPLAY_MODE = 'SET_DISPLAY_MODE';

export const UPDATE_MATCHDAY = 'UPDATE_MATCHDAY';

export const BEGIN_LOAD_MATCHES = 'BEGIN_LOAD_MATCHES';
export const BEGIN_LOAD_STANDINGS = 'BEGIN_LOAD_STANDINGS';
export const BEGIN_LOAD_TEAMS = 'BEGIN_LOAD_TEAMS';

export const LOAD_MATCHES_SUCCESS = 'LOAD_MATCHES_SUCCESS';
export const LOAD_STANDINGS_SUCCESS = 'LOAD_STANDINGS_SUCCESS';
export const LOAD_TEAMS_SUCCESS = 'LOAD_TEAMS_SUCCESS';
